### ISSUE TITLE
Python issue that occurs when importing library

### ISSUE THREAD

**Issue by chrisiacovella** [shirtsgroup/physical_validation#33]
When I import the physical validation package, i.e., 
```
import physical_validation as pv
```
I get the error: 

```
Traceback (most recent call last):
  File "ana_flatfile.py", line 2, in <module>
    import physical_validation as pv
  File "/Users/cri/anaconda3/lib/python2.7/site-packages/physical_validation/__init__.py", line 43, in <module>
    from . import kinetic_energy
  File "/Users/cri/anaconda3/lib/python2.7/site-packages/physical_validation/kinetic_energy.py", line 36, in <module>
    from .util import kinetic_energy as util_kin
  File "/Users/cri/anaconda3/lib/python2.7/site-packages/physical_validation/util/__init__.py", line 31, in <module>
    from . import ensemble
  File "/Users/cri/anaconda3/lib/python2.7/site-packages/physical_validation/util/ensemble.py", line 774
    '[0/{:d}]'.format(bs_repetitions), end='')
                                          ^
SyntaxError: invalid syntax
```

Note, on this machine I am running:  Python 2.7.15 :: Anaconda, Inc.

**Comment by ptmerz** [comment]
Thanks a lot for the report, that was a compatibility problem with python 2.7. Should be fixed now!
