### ISSUE TITLE
String formatting issue in kinetic energy check_mean_std

### ISSUE THREAD

**Issue by cwalker7** [shirtsgroup/physical_validation#75]
I'm working on applying physical validation to OpenMM simulations and ran into an error with the formatting in the non-strict version of the kinetic energy test:

```python3
Traceback (most recent call last):
  File "physical_validation_openmm_KE_6_22_20.py", line 86, in <module>
    pv.kinetic_energy.distribution(sim_data,strict=False,filename='KE_test_nonstrict')
  File "/projects/chwa2399/software/anaconda/envs/cg_openmm_5_29/lib/python3.6/site-packages/physical_validation/kinetic_energy.py", line 155, in distribution
    temp_unit=data.units.temperature_str,
  File "/projects/chwa2399/software/anaconda/envs/cg_openmm_5_29/lib/python3.6/site-packages/physical_validation/util/kinetic_energy.py", line 385, in check_mean_std
    std_temp_sig,
TypeError: unsupported format string passed to numpy.ndarray.__format__
```

I'm using python 3.6 and numpy 1.18.4 - is this a python version issue? The strict test has no problems.

**Comment by mattwthompson** [comment]
It looks like there are issues with the `{ }` vs `%` formatting in numpy (see https://github.com/numpy/numpy/issues/12491, in which the source code here seems to be using the buggy of the two)

**Comment by ptmerz** [comment]
Can you still observe the problem @cwalker7? If yes, could you upload input data to reproduce it? I don't seem to be able to reproduce it.

**Comment by ptmerz** [comment]
Closed since it can't be reproduced with current version. Please reopen if the problem is observed again.
